### PR TITLE
Feature/tracking page

### PR DESCRIPTION
**Pull request by GyuoMi**
updated drawer for tracking and devices page
some changes are still coming from @peppermintCoffee for creating records
added device deletion
conditional popup dialog for either adding or editing
device page now refreshes upon adding or editing

### CODE REVIEW

**Comment by GyuoMi** [comment]
also added `await` thanks to @SahilDinanath under deleteDevice so that it deletes from setup_tbl first and then from device_tbl

**Comment by SahilDinanath** [comment]
Success, so clearly in view. Or, is it merely a trick of the light?

**Review by SahilDinanath — APPROVED** [review]

**Comment by GyuoMi** [comment]
> Success, so clearly in view. Or, is it merely a trick of the light?

i am blind af

**Comment by SahilDinanath** [comment]
True desperation is known only when escape is impossible.

**Comment by GyuoMi** [comment]
image

**Pull request merged**
